### ISSUE TITLE
Where is the Downloadable Output available in Source Control?

### ISSUE THREAD

**Issue by ricklove** [morphgnt/tischendorf#1]
At:
https://github.com/morphgnt/tischendorf/downloads/

The Readme includes this information:

```
        Tischendorf's 8th edition Greek New Testament
                   with morphological tags
                         Version 2.6

          Based on G. Clint Yale's Tischendorf text
               and on Dr. Maurice A. Robinson's
               Public Domain Westcott-Hort text

      Edited by Ulrik Sandborg-Petersen
```

In the zip are txt files which contain a unicode version. For example:
- JAS 1:1.1 C Ἰάκωβος Ἰάκωβος N-NSM 2385 Ἰάκωβος ! Ἰάκωβος
- JAS 1:1.2 . θεοῦ θεοῦ N-GSM 2316 θεός ! θεός

I cannot find these files anywhere in the source code or any reference to them.

It would be good to add this to the source code and add a README.md file to expain the file structure. I can do this in my fork and send you a pull request when I am done, if you give me some guidance.

I am interested in the Tischendorf Text because it is public domain while the SBL is not.

**Comment by emg** [comment]
Hello,

thanks for opening an issue for the Tischendorf project in 2014.  I am really sorry for the long delay.

Since then, a README.md has been added, which might take care of your question.

Moreover, version 2.8 was released today. It includes the same word-per-line text that was available in previous versions (but with 700 corrections). It also, as something new, includes a version in OSIS XML format.

Hope this helps.

Best wishes,

Ulrik Sandborg-Petersen
